[package]
name = "PushNotificationsService"
version = "0.1.0"
authors = ["edgeone <edgeone@ya.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
tonic = { version = "0.3.1", features = ["tls"] }
prost = "0.6"
tokio = { version = "0.2.22", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds"] }
#tokio = { version = "0.3.2", features = ["rt-multi-thread", "time", "stream", "fs", "macros", "net", "sync"] }
futures = "0.3"


[build-dependencies]
tonic-build = "0.2.0"

[profile.release]
opt-level = 'z'
lto = true # enable link time optimization

[profile.dev]
opt-level = 0
lto = false # enable link time optimization
